---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-resources.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: openchoreo-data-plane-values
    namespace: openchoreo-data-plane
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
