---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - control-plane.yaml
  - data-plane.yaml
  - build-plane.yaml
  - observability-plane.yaml
  # plane-registrations.yaml moved to separate Flux Kustomization
  # to ensure CRDs exist before plane CRs are created
